// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkHumTJ1owGDGMTmQCfdSgJ8tNIdQ3rCo',
    appId: '1:410748627345:web:ac8789d3ff26db5a10d230',
    messagingSenderId: '410748627345',
    projectId: 'streamscapefire',
    authDomain: 'streamscapefire.firebaseapp.com',
    storageBucket: 'streamscapefire.firebasestorage.app',
    measurementId: 'G-J8L8G9QLBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCquv7eXe7Cwn_UO4vD77VurafPrGixDpY',
    appId: '1:410748627345:android:e30560ab201ffdc310d230',
    messagingSenderId: '410748627345',
    projectId: 'streamscapefire',
    storageBucket: 'streamscapefire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIV6Jj2XMQrExrxQ_QHnTzCjCi_5f-bms',
    appId: '1:410748627345:ios:a5904c0ce04589b510d230',
    messagingSenderId: '410748627345',
    projectId: 'streamscapefire',
    storageBucket: 'streamscapefire.firebasestorage.app',
    iosBundleId: 'com.example.azakarstream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIV6Jj2XMQrExrxQ_QHnTzCjCi_5f-bms',
    appId: '1:410748627345:ios:a5904c0ce04589b510d230',
    messagingSenderId: '410748627345',
    projectId: 'streamscapefire',
    storageBucket: 'streamscapefire.firebasestorage.app',
    iosBundleId: 'com.example.azakarstream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkHumTJ1owGDGMTmQCfdSgJ8tNIdQ3rCo',
    appId: '1:410748627345:web:8fc68be438f2924010d230',
    messagingSenderId: '410748627345',
    projectId: 'streamscapefire',
    authDomain: 'streamscapefire.firebaseapp.com',
    storageBucket: 'streamscapefire.firebasestorage.app',
    measurementId: 'G-X5BFZSLH5J',
  );

}